# Generated by Django 4.0.1 on 2022-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_datetime', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_home_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_away_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_predicted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('csv', models.FileField(upload_to='media/csv/')),
            ],
        ),
    ]
